collectors: []
extraArgs:
  - --custom-resource-state-only=true
rbac:
  extraRules:
    - apiGroups:
        - apps
      resources:
        - deployments
      verbs: ["list", "watch"]
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: apps
            version: v1
            kind: Deployment
          metricNamePrefix: deploystate
          metrics:
            - name: "deployment_dummy_metric"
              help: "Dummy constant metric for deployments"
              each:
                type: Gauge
                gauge:
                  constantValue: 42

