collectors: []
extraArgs:
  - --custom-resource-state-only=true
rbac:
  extraRules:
    - apiGroups:
        - ""
      resources:
        - pods
      verbs: ["list", "watch"]
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: ""
            version: v1
            kind: Pod
          metricNamePrefix: podstate
          metrics:
            - name: "pod_dummy_metric"
              help: "Dummy constant metric for pods"
              each:
                type: Gauge
                gauge:
                  constantValue: 42
