    collectors: []
    extraArgs:
      - --custom-resource-state-only=true
    rbac:
      extraRules:
        - apiGroups:
            - source.toolkit.fluxcd.io
            - kustomize.toolkit.fluxcd.io
            - helm.toolkit.fluxcd.io
            - notification.toolkit.fluxcd.io
            - image.toolkit.fluxcd.io
          resources:
            - gitrepositories
            - buckets
            - helmrepositories
            - helmcharts
            - ocirepositories
            - kustomizations
            - helmreleases
            - alerts
            - providers
            - receivers
            - imagerepositories
            - imagepolicies
            - imageupdateautomations
    customResourceState:
      enabled: true
      config:
        spec:
          resources:
            - groupVersionKind:
                group: kustomize.toolkit.fluxcd.io
                version: v1
                kind: Kustomization
              metricNamePrefix: gotk
              metrics:
                - name: "resource_info"
                  help: "The current state of a Flux Kustomization resource."
                  each:
                    type: Untyped
                    untyped:
                      value: 1
                      labelsFromPath:
                        name: [ name ]
