collectors: []
extraArgs:
  - --custom-resource-state-only=true
rbac:
  extraRules:
    - apiGroups:
        - ""  # core API group
      resources:
        - services
      verbs: ["list", "watch"]
customResourceState:
  enabled: true
  config:
    spec:
      resources:
        - groupVersionKind:
            group: "networking.k8s.io"          # core group
            version: v1
            kind: Service
          metricNamePrefix: svcstate
          metrics:
            - name: "service_dummy_metric"
              help: "Dummy constant metric for services"
              each:
                type: Gauge
                gauge:
                  constantValue: 42

