apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-minio
  namespace: monitoring
  labels:
    app: test-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-minio
  template:
    metadata:
      labels:
        app: test-minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2023-07-18T23-52-14Z
        args:
          - server
          - /data
        ports:
        - containerPort: 9000
        env:
          - name: MINIO_ROOT_USER
            value: "minioadmin"
          - name: MINIO_ROOT_PASSWORD
            value: "minioadmin"
        volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: test-minio
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: http
  selector:
    app: test-minio
