apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-metrics
  template:
    metadata:
      labels:
        app: dummy-metrics
    spec:
      containers:
      - name: dummy
        image: ghcr.io/ricardlom/dummy-prometheus-metrics:latest
        ports:
        - containerPort: 8000
