apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  releaseName: kube-state-metrics
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: "6.1.0" 
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: kube-state-metrics-values
      valuesKey: kube-state-metrics-config.yaml
